library(readr)
library(dplyr)
library(purrr)

parse_gamelogs <- function(gamelog_files) {
  # Column names per Retrosheet's glfields.txt
  # https://www.retrosheet.org/gamelogs/glfields.txt
  gl_cols <- c(
    "game_date",
    "game_num",
    "day_of_week",
    "v_team",
    "v_league",
    "v_game_num",
    "h_team",
    "h_league",
    "h_game_num",
    "v_score",
    "h_score",
    "length_outs",
    "day_night",
    "completion",
    "forfeit",
    "protest",
    "park_id",
    "attendance",
    "time_of_game",
    "v_line_score",
    "h_line_score",
    "v_ab",
    "v_h",
    "v_2b",
    "v_3b",
    "v_hr",
    "v_rbi",
    "v_sh",
    "v_sf",
    "v_hbp",
    "v_bb",
    "v_ibb",
    "v_so",
    "v_sb",
    "v_cs",
    "v_gdp",
    "v_ci",
    "v_lob",
    "v_pitchers_used",
    "v_indiv_er",
    "v_team_er",
    "v_wp",
    "v_balks",
    "v_po",
    "v_a",
    "v_e",
    "v_passed_balls",
    "v_dp",
    "v_tp",
    "h_ab",
    "h_h",
    "h_2b",
    "h_3b",
    "h_hr",
    "h_rbi",
    "h_sh",
    "h_sf",
    "h_hbp",
    "h_bb",
    "h_ibb",
    "h_so",
    "h_sb",
    "h_cs",
    "h_gdp",
    "h_ci",
    "h_lob",
    "h_pitchers_used",
    "h_indiv_er",
    "h_team_er",
    "h_wp",
    "h_balks",
    "h_po",
    "h_a",
    "h_e",
    "h_passed_balls",
    "h_dp",
    "h_tp",
    "hp_ump_id",
    "hp_ump_name",
    "1b_ump_id",
    "1b_ump_name",
    "2b_ump_id",
    "2b_ump_name",
    "3b_ump_id",
    "3b_ump_name",
    "lf_ump_id",
    "lf_ump_name",
    "rf_ump_id",
    "rf_ump_name",
    "v_manager_id",
    "v_manager_name",
    "h_manager_id",
    "h_manager_name",
    "winning_pitcher_id",
    "winning_pitcher_name",
    "losing_pitcher_id",
    "losing_pitcher_name",
    "saving_pitcher_id",
    "saving_pitcher_name",
    "gwrbi_id",
    "gwrbi_name",
    "v_sp_id",
    "v_sp_name",
    "h_sp_id",
    "h_sp_name",
    "v_bat1_id",
    "v_bat1_name",
    "v_bat1_pos",
    "v_bat2_id",
    "v_bat2_name",
    "v_bat2_pos",
    "v_bat3_id",
    "v_bat3_name",
    "v_bat3_pos",
    "v_bat4_id",
    "v_bat4_name",
    "v_bat4_pos",
    "v_bat5_id",
    "v_bat5_name",
    "v_bat5_pos",
    "v_bat6_id",
    "v_bat6_name",
    "v_bat6_pos",
    "v_bat7_id",
    "v_bat7_name",
    "v_bat7_pos",
    "v_bat8_id",
    "v_bat8_name",
    "v_bat8_pos",
    "v_bat9_id",
    "v_bat9_name",
    "v_bat9_pos",
    "h_bat1_id",
    "h_bat1_name",
    "h_bat1_pos",
    "h_bat2_id",
    "h_bat2_name",
    "h_bat2_pos",
    "h_bat3_id",
    "h_bat3_name",
    "h_bat3_pos",
    "h_bat4_id",
    "h_bat4_name",
    "h_bat4_pos",
    "h_bat5_id",
    "h_bat5_name",
    "h_bat5_pos",
    "h_bat6_id",
    "h_bat6_name",
    "h_bat6_pos",
    "h_bat7_id",
    "h_bat7_name",
    "h_bat7_pos",
    "h_bat8_id",
    "h_bat8_name",
    "h_bat8_pos",
    "h_bat9_id",
    "h_bat9_name",
    "h_bat9_pos",
    "additional_info",
    "acquisition_info"
  )

  # Read and combine all gamelog files
  map(gamelog_files, function(f) {
    read_csv(
      f,
      col_names = gl_cols,
      col_types = cols(.default = "c"), # read all as character first
      show_col_types = FALSE
    )
  }) |>
    list_rbind() |>
    mutate(
      game_date = as.Date(as.character(.data$game_date), format = "%Y%m%d"),
      season = as.integer(format(game_date, "%Y")),
      v_score = as.integer(v_score),
      h_score = as.integer(h_score),
      attendance = as.integer(attendance),
      across(c(v_ab:v_tp, h_ab:h_tp), as.integer)
    )
}
